# Generated by Django 6.0.5 on 2026-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Afiliado'),
        ),
    ]
